# Generated by Django 3.2 on 2022-06-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
